# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: BIN-GO
email: daib09physics@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is Bin Dai's personal website. I will post my reading comments, 
  research achievements and other interesting things in life here.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://daib13.github.io/" # the base hostname & protocol for your site
github_username:  daib13

# Build settings
markdown: kramdown
